version: "3.9"

services:
  scrooge:
    container_name: scrooge
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    depends_on:
      - db
  
  db:
    container_name: postgres
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - 5432:5432

volumes:
  postgres-data:
