# Generated by Django 4.2.6 on 2023-11-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='category',
            field=models.ForeignKey(limit_choices_to={'payment_method': 'Non-cash'}, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='expense.billscategory'),
        ),
    ]
