# Generated by Django 4.2.6 on 2023-11-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_bills_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__payment_method': 'Non-cash'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.bills'),
        ),
    ]
