# Generated by Django 4.2.6 on 2023-11-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_user_alter_savings_user_billsaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billsaccount', to='expense.bills'),
        ),
    ]
