# Generated by Django 4.2.6 on 2023-11-25 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0005_alter_billsaccount_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.billsaccount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userexpenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
