# Generated by Django 4.2.6 on 2023-11-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expense_bill_account_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bill',
        ),
        migrations.AlterField(
            model_name='expense',
            name='bill_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__payment_method': 'Non-cash'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.billsaccount'),
        ),
    ]
