# Generated by Django 4.2.6 on 2023-11-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_remove_bills_amount_remove_bills_amount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.wallet'),
        ),
    ]
