# Generated by Django 4.2.6 on 2023-11-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_bill'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='bill_id',
            field=models.ForeignKey(limit_choices_to={'category__payment_method': 'Non-cash'}, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='expense.bills'),
        ),
    ]
