# Generated by Django 4.2.6 on 2023-11-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomecategory', to='income.incomecategory'),
        ),
    ]
