# Generated by Django 4.2.6 on 2023-11-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_remove_expense_user_alter_expense_bill_account'),
        ('income', '0003_alter_income_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='bill_id',
        ),
        migrations.AddField(
            model_name='income',
            name='bill_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='expense.billsaccount'),
        ),
    ]
